name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ] # Intercetta tag come v1.0.0, v2.1.3, ecc.
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Assicurati che il Dockerfile sia nella root del progetto
          push: true
          tags: fujicicimolly/muscolino:latest
